//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boilerplate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int sales_id { get; set; }
        public int product_id { get; set; }
        public int customer_id { get; set; }
        public int store_id { get; set; }
        public System.DateTime date_sold { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
        public virtual Store Store { get; set; }
    }
}
